from typing import Protocol


class FavoriteRepository(Protocol):
    async def add_favorite(self, telegram_id: int, game_id: int) -> None: ...
    async def remove_favorite(self, telegram_id: int, game_id: int) -> None: ...
    async def list_favorite_ids(self, telegram_id: int) -> list[int]: ...

